zombodb/zombodb

elasticsearch/src/main/java/com/tcdi/zombodb/postgres/PostgresTIDResponseAction.java
postgres/src/main/c/am/elasticsearch.c
postgres/src/main/c/am/elasticsearch.h
postgres/src/main/c/am/zdb_interface.c
postgres/src/main/c/am/zdb_interface.h
postgres/src/main/c/am/zdbam.c

First, we only test rows for deletion that might actually be dead (_xmax_is_committed:true or _xmin_is_committed:false).  This reduces the total number of rows we need to examine to what's likely the complete set, rather than needing to inspect each and every row in the index.  So instead of looking at 20M+ rows, we just look at the 50k that have been UPDATEd or DELETEd.
Secondly, when building the internal set of ItemPointers to actually delete, use a `List` instead of manually growing/copying a `char *`.
This also renames the "getAllItems" function to "getPossiblyExpiredItems" because that's what it does, and "get all items" isn't a thing we do anywhere.

Close issue #15

---

SQL-API.md
elasticsearch/src/main/java/com/tcdi/zombodb/postgres/PostgresAggregationAction.java
elasticsearch/src/main/java/com/tcdi/zombodb/query_parser/QueryRewriter.java
postgres/src/test/expected/issue-29.out
postgres/src/test/sql/issue-29.sql
postgres/src/test/tests.list

QueryRewriter.java was hardcoding zero as the .size() argument to the TermsBuilder, which means "get everything".  This change sets it to the value provided by the user in their call to zdb_tally().  A user-provided value of zero now means "get everything".
The .shardSize() argument is still hardcoded to zero, which means that ES will be as precise as it possibly can when pulling terms from each shard.
Thanks to @ryancutter for the report and discussion.
Also:
- Aggregation execution time logging was stupidly logging before the aggregate actually finished.
- a test to make sure results from zdb_tally() are indeed limited by the 'max_terms' argument.

fix issue #29:  Use the "max_terms" value for tally aggregate function

---

.gitignore
README.md
SQL-API.md
docker/elasticsearch/Dockerfile
docker/postgres/Dockerfile
elasticsearch/pom.xml
elasticsearch/src/main/java/com/tcdi/zombodb/ZombodbPlugin.java
elasticsearch/src/main/java/com/tcdi/zombodb/postgres/ZombodbMultisearchAction.java
pom.xml
postgres/pom.xml
postgres/src/main/c/am/elasticsearch.c
postgres/src/main/c/am/elasticsearch.h
postgres/src/main/c/am/zdb_interface.c
postgres/src/main/c/am/zdb_interface.h
postgres/src/main/c/am/zdbops.c
postgres/src/main/c/am/zdbops.h
postgres/src/main/c/util/zdbutils.c
postgres/src/main/c/util/zdbutils.h
postgres/src/main/sql/zombodb--2.5.6--2.5.7.sql
postgres/src/main/sql/zombodb.sql
postgres/src/test/expected/multi-search.out
postgres/src/test/sql/multi-search.sql
postgres/src/test/tests.list
postgres/zombodb.control

This pull request implements functionality to search multiple tables at the same time.  The tables can either be searched with the same query, or each searched with different queries.  The results include the "top 10" (ordered by score desc) matching documents from each table (including partial `row_to_json()` data).
The returned row data purposely omits any columns of type `fulltext` for performance reasons -- testing showed that including these would make the total execution time over 20x slower.  This seems like a fair compromise as if you're searching multiple tables at a time, you likely only want to show the user a summary of what was found.
SQL-level functions exist for searching an array of tables/views with the same query, or searching an array of tables/views each with their own …

Search many tables at once

---

elasticsearch/src/main/java/com/tcdi/zombodb/postgres/PostgresAggregationAction.java
elasticsearch/src/main/java/com/tcdi/zombodb/postgres/PostgresCountAction.java
elasticsearch/src/main/java/com/tcdi/zombodb/postgres/PostgresMappingAction.java
elasticsearch/src/main/java/com/tcdi/zombodb/postgres/PostgresTIDResponseAction.java
elasticsearch/src/main/java/com/tcdi/zombodb/postgres/ZombodbMultiSearchAction.java
elasticsearch/src/main/java/com/tcdi/zombodb/postgres/ZombodbQueryAction.java
elasticsearch/src/main/java/com/tcdi/zombodb/query_parser/QueryRewriter.java
elasticsearch/src/test/java/com/tcdi/zombodb/test/ZomboDBTestCase.java
postgres/src/main/c/am/zdb_interface.c
postgres/src/main/c/am/zdb_interface.h
postgres/src/main/c/am/zdbam.c

improve performance when doing "joins" to other indexes by using an aggregate, along with using a terms filter, query caching, and one less round-trip to zdb_estimate_count() during query planning

resolving issue #91:

---

elasticsearch/src/main/resources/es-plugin.properties

Will adding a version key to the es-plugin.properties file have it properly report the installed version?
Example:
`http://localhost:9200/_cat/plugins`
Before:
```
nodename  marvel  1.3.1 j/s /_plugin/marvel/ 
nodename  Zombodb NA    j                    
```
After:
```
nodename  marvel  1.3.1 j/s /_plugin/marvel/ 
nodename  Zombodb x.y.z j
```

report zombodb version

---

.gitignore
elasticsearch/src/main/java/com/tcdi/zombodb/query_parser/optimizers/ExpansionOptimizer.java
elasticsearch/src/main/java/com/tcdi/zombodb/query_parser/optimizers/IndexLinkOptimizer.java
elasticsearch/src/main/java/com/tcdi/zombodb/query_parser/rewriters/SirenQueryRewriter.java
postgres/Makefile
postgres/src/test/zdbtaptests/sql/setup.sql
postgres/src/test/zdbtaptests/tests/build-same.sh

This fixes issue #185 and adds an auto-generated (during `make installcheck` or `make pgtap`) tap test called `expand-same.sql`.  
The generated test uses all the source ZDB queries from `expand.sql` and compares them to the new view (and its corresponding tables) to ensure the results are the same.

fixing issue #185. 

---

elasticsearch/src/main/java/llc/zombodb/cross_join/CrossJoinQuery.java
elasticsearch/src/main/java/llc/zombodb/cross_join/CrossJoinQueryRewriteHelper.java
elasticsearch/src/main/java/llc/zombodb/fast_terms/TransportFastTermsAction.java
elasticsearch/src/main/java/llc/zombodb/rest/search/ZomboDBCountAction.java

1) Detect non-started shards in TransportFastTermsAction
2) Better handle shard errors and no-responses in TransportFastTermsAction
3) Don't override .rewrite() in CrossJoinQuery, instead do the rewrite in
.createWeight() so that we run the FastTermsAction after ES has had an
opportunity to cache our query
4) Remove the internal caching ZDB was doing in CrossJoinQuery as it's not
actually necessary
5) Teach ZomboDBCountAction to detect shard failures and return an error
instead

fixing issue #257

---

.gitignore
CONFIGURATION-SETTINGS.md
README.md
THINGS-TO-KNOW.md
src/c/elasticsearch/elasticsearch.c
src/c/elasticsearch/elasticsearch.h
src/c/indexam/zdbam.c
src/c/indexam/zdbam.h
src/c/indexam/zdbfuncs.c
src/c/json/json.c
src/c/json/json.h
src/c/utils/utils.h
src/c/zombodb.h
src/flint/gcc-include-path.lnt
src/flint/lint_cmac.h
src/flint/lint_cppmac.h
src/sql/mvcc-visibility.sql
src/sql/zombodb--10-1.0.0b4--10-1.0.0b5.sql
src/test/expected/issue-273.out
src/test/expected/test-batch_mode.out
src/test/expected/test-copy.out
src/test/expected/test-zdbl_visibility_clause.out
src/test/sql/issue-273.sql
src/test/sql/test-batch_mode.sql
src/test/sql/test-copy.sql
src/test/sql/test-zdbl_visibility_clause.sql
zombodb.control

This resolves Issue #273 by adding support for `SAVEPOINT` and `ROLLBACK TO`.
It also removes the `zdb.batch_mode` GUC setting as operating in "batch mode" is now what ZDB does all the time.  If in the middle of a transaction ZDB sees that it needs to push current batches to Elasticsearch in order to be able to properly answer a SELECT statement (or any of the zdb.agg() functions) then it does that automatically.

Resolve Issue 273

---

.gitignore
Makefile
QUERY-DSL.md
TYPE-MAPPING.md
src/c/elasticsearch/elasticsearch.c
src/c/elasticsearch/elasticsearch.h
src/c/elasticsearch/querygen.c
src/c/elasticsearch/querygen.h
src/c/highlighting/highlighting.c
src/c/highlighting/highlighting.h
src/c/indexam/seqscan.c
src/c/indexam/zdb_index_options.h
src/c/indexam/zdbam.c
src/c/indexam/zdbfuncs.c
src/c/zombodb.h
src/sql/analyze-support.sql
src/sql/highlight-support.sql
src/sql/join-support.sql
src/sql/mapping.sql
src/sql/query-dsl.sql
src/sql/zombodb--10-1.0.1--10-1.0.2.sql
src/test/expected/test-zdb_ignore_visibility.out
src/test/sql/test-zdb_ignore_visibility.sql
zombodb.control

Prior to this PR, ZomboDB would apply a "visibility query" to every Elasticsearch query executed, including those executed for a normal SELECT statement.
The visibility query is required, in general, to ensure that research results don't include rows which are invisible to the executing transaction.  In the case of SELECT statements, however, Postgres will filter those rows out for us, even if ZDB returns them from Elasticsearch.  This turns out to be significantly faster.
It's still necessary for ZomboDB to apply its "visibility query" for SELECT queries that include a LIMIT clause, and also necessary for all of the Elasticsearch aggregate types that ZomboDB exposes as top-level functions, such as `zdb.terms()`.
Using a very simple pg_bench test, on my laptop, this is how ZDB performed …

Reduce per-SELECT overhead

---

src/c/rest/rest.c

Currently, the HTTP version is set to HTTP/1.1 and then later in the same function set to HTTP/1.0.  This PR fixes that so that HTTP/1.1 is used.
I found this one deploying to a k8s cluster with istio, which does not support HTTP/1.0 by default between containers.

use HTTP/1.1

---

.gitignore
.travis.yml
INSTALL.md
README.md
docker/elasticsearch/Dockerfile
docker/postgres/Dockerfile
elasticsearch/pom.xml
elasticsearch/src/main/assemblies/plugin.xml
elasticsearch/src/main/resources/plugin-descriptor.properties
pom.xml
postgres/pom.xml
postgres/src/main/shell/hack-configs-for-travisci.sh
postgres/src/main/sql/zombodb--5.6.4-1.0.17--5.6.16-1.0.18.sql
postgres/zombodb.control

This PR changes ZDB's ES 5.6 support branches from 5.6.4 to 5.6.16.
This change is necessary to that ZDB users won't be affected by this ES bug:  https://github.com/elastic/elasticsearch/pull/36770, which apparently is fairly easy for ZDB to trigger b/c of its concurrent indexing requests

upgrade from supporting ES v5.6.4 to ES v5.6.16

---

POSTGIS-SUPPORT.md

Update the PostGIS documentation to refer to the proper function used to ensure data is in the WGS84 CRS.  `ST_Transform()` performs the described function (used [here](https://github.com/zombodb/zombodb/blob/d30253af4e819fc40880ae7b72b64285644ea312/sql/_postgis-support.sql#L13-L15)).
https://postgis.net/docs/ST_Transform.html
`ST_Translate()` moves spatial data on the x/y/z planes.  https://postgis.net/docs/ST_Translate.html

Update PostGIS to reference ST_Transform instead of ST_Translate

---

INDEX-MANAGEMENT.md
README.md
src/json/utils.rs

Fix json-escape bug with non-ascii character, which corrupts text field while pushing document into Elasticsearch.

fix json-escape with non-ascii character

---

INDEX-MANAGEMENT.md
README.md
SOURCE-INSTALLATION.md

zombodb requires `make` during build (from cargo-pgx maybe?), so specify the dependency in a document.

specify missing dependency

---

INDEX-MANAGEMENT.md
README.md
src/elasticsearch/bulk.rs

I discovered the `drain(0..).collect()` while tracking down #647, which could be replaced with `std::mem::take` https://doc.rust-lang.org/stable/std/mem/fn.take.html
It's just a minor nitpick, so feel free to merge or close :)

replaces drain(0..).collect() with take()

---

README.md

The render of the markdown table on GitHub is also fixed by this tiny patch.

Fixed system requirements table format

---

README.md

- Added Postgres `14.x`
- Require Elasticsearch to be `>=7.10` as `case_insensitive` for prefix queries was not supported below that, which ZDB requires since (at least) 852bd35ee113718dcc9ab9b5d6d56f4ad7a1ed9a

Update System Requirements in README.md

---

SQL-FUNCTIONS.md
sql/_mappings.sql
src/mapping/mod.rs
test/expected/issue-770.out
test/sql/issue-770.sql

This adds a few more allowed time formats for the `time with(out) time zone` types.
It also adds a new function named `zdb.reapply_mapping(regclass)` that can be used to reapply the index mapping when a "mapping thing" changes, such as a row in the `zdb.type_mappings` table.

fix issue #770

---

src/executor_manager/mod.rs
src/highlighting/es_highlighting.rs
src/walker/mod.rs

This is a PoC for #773 that implements `zdb.highlight(ctid)`, which fetches all highlights regardless of field name.
(Please note that I'm no expert in any of Elasticsearch, PGX or Rust and it's been a while since I last dabbled in PG internals.)
Another API design issue to be aware of, is that to pass highlight options, one has to explicitly cast the optional second argument to JSON:
```sql
-- Assumes the second argument is the field name, calls highlight_field(), does not work correctly.
SELECT zdb.highlight(ctid, '{...}') FROM table;
-- Calls highlight_all_fields(), works correctly.
SELECT zdb.highlight(ctid, '{...}'::json) FROM table;
```

implement single-arg `zdb.highlight()` to fetch all highlights

---

src/elasticsearch/bulk.rs

This also drops the bulk indexing channel bound to "concurrency", which is the `MIN(#cpus, #shards)`.  There's no reason to buffer any more than we could potentially handle at once.  This might slightly improve memory consumption during indexing, hopefully without hurting indexing performance.

fix issue #797 - don't hardcode `10_000` (the `queue_size`) everywhere.

---

src/zql/transformations/prox_rewriter.rs
test/expected/issue-822.out
test/sql/issue-822.sql

searching with a wildcard at the end of a date (ie, as a prefix query) no longer converts to a proximity query

fix issue #822 - searching with a wildcard at the end of a date

---

docker-build-system/package.sh
src/access_method/rewriter.rs
test/expected/test-update-wrong-attribute-type.out
test/sql/test-update-wrong-attribute-type.sql

It's possible for an UPDATE statement in the form of:  `UPDATE t SET f = 'v' WHERE i IN (SELECT i FROM t WHERE t ==> <zdb query>` to cause an error like:
```
ERROR:  attribute 112 of type record has wrong type
DETAIL:  Table has type tid, but query expects s.t.
```
It also seems a view and trigger needs to be involved.  Definitely an edge-case bug.
Seemingly this can then lead to future segfaults, although I have not been able to recreate the segfault.

Explore update ERROR/crash

---

src/highlighting/document_highlighter.rs
src/highlighting/query_highlighter.rs
src/zql/ast.rs
src/zql/dsl/mod.rs
src/zql/parser.lalrpop
test/expected/issue-852.out
test/sql/issue-852.sql

This required inventing that new Term variant and plumbing it through the code.

fix issue #852 - querying for an empty array will now `match_none`.

---

installcheck
src/access_method/options.rs
test/expected/legacy/issue-83.out
test/sql/legacy/issue-83.sql

This teaches the `zdb.field_mapping()` field how to resolve fields that are a) in other indexes, and b) actually a named index itself.  This restores compatibility with the old `zdb_describe_nested_object()` function from the pre-3k days.
Fixes issue #857

fix issue #857

---

src/highlighting/query_highlighter.rs
test/expected/issue-861.out
test/sql/issue-861.sql

`zdb.highlight_document()` now properly understands the bare `*` (MatchAll) wildcard

fix issue #861

---

Cargo.lock
Cargo.toml
src/highlighting/document_highlighter.rs
src/highlighting/query_highlighter.rs
test/expected/issue-812.out
test/expected/issue-836.out
test/expected/issue-863.out
test/sql/issue-863.sql

This adjusts hit highlighting to only remove "shingle" hits during final hit de-duplication if the "shingle" hit is not unique relative to the current hit being emitted.
This does adjust the expected output for issue #812, but after discussion with @Shigoki, we believe this is the correct behavior.
Also updates pgrx to 0.9.8.

Fix issue #863

---

src/zql/transformations/index_links.rs
test/expected/issue-864.out
test/sql/issue-864.sql

The `WITH` operator now properly joins linked fields into a single `Expr::WithList` expression, or panics if the fields are from disparate index links.

Fix issue #864

---

src/zql/ast.rs
src/zql/transformations/index_links.rs
src/zql/transformations/merge_index_links.rs
src/zql/transformations/mod.rs
test/expected/issue-679.out
test/expected/issue-867.out
test/sql/issue-679.sql
test/sql/issue-867.sql

The unary `NOT` operator is now pushed down into `Expr::Linked` nodes which is where it should be.  This ensures we're not retrieving values from ES that we shouldn't, which may not be properly filtered if the NOT was on the outside.
This does change the test around issue #679, but that was fixed incorrectly in the first place, which lead to this bug.

Fix issue #867

---

src/access_method/vacuum.rs
src/elasticsearch/bulk.rs
test/expected/issue-869.out
test/sql/issue-869.sql

`VACUUM (PARALLEL)` no longer cancels itself.
There's some other little cleanup here around returning an `IndexBulkDeleteResult` just to be consistent with how the other core Postgres index types do it.

Fix issue #869

---

.gitignore
Cargo.lock
Cargo.toml
SOURCE-INSTALLATION.md
src/elasticsearch/mod.rs

This PR adds TLS support either via controllable feature-flags through the following crates:
- `rustls` (along with native OS certs)
- `native-tls`
I have added some documentation entries to explain how it works. Tested against self-signed certificates generated with `elasticsearch-certutil` on version 8.9.1. 
Solves: 
- https://github.com/zombodb/zombodb/issues/872
- https://github.com/zombodb/zombodb/issues/827

Add TLS support in Elasticsearch client

---

src/highlighting/document_highlighter.rs
test/expected/issue-807.out
test/sql/issue-807.sql

This fixes a problem related to the work done in #807 where ZDB would panic with `ERROR:  called Option::unwrap() on a None value` when trying to highlight a NULL value using one of the range operators like `>=` or `<=`.

Follow up fix for #807

---

src/elasticsearch/mod.rs
src/zql/ast.rs
src/zql/transformations/mod.rs
src/zql/transformations/pullup.rs
test/expected/issue-901.out
test/sql/issue-901.sql

Nested `AndList` nodes need to be pulled up into the to-level node so as to avoid subsequent transformations from misunderstanding where fields come from.
Also added ability to log, at `DEBUG1` the url and post body when we call to ES

fix issue #901
