- .travis.yml
- README.md
- elasticsearch/pom.xml
- elasticsearch/src/main/java/com/tcdi/zombodb/postgres/PostgresCountAction.java
- elasticsearch/src/main/java/com/tcdi/zombodb/postgres/PostgresMappingAction.java
- elasticsearch/src/main/java/com/tcdi/zombodb/postgres/util/OverloadedContentRestRequest.java
- elasticsearch/src/test/java/com/tcdi/zombodb/query_parser/TestQueryRewriter.java
- elasticsearch/src/test/resources/com/tcdi/zombodb/query_parser/testIt.expected
Reverted the change for the test case.  Order is different on my local box.
Cut and paste error, fixed
Updated so that it is using the 1.7 version of es
> Updated the elasticsearch jar to 1.7.1

- SQL-API.md
- elasticsearch/src/main/java/com/tcdi/zombodb/query_parser/QueryRewriter.java
- elasticsearch/src/test/java/com/tcdi/zombodb/query_parser/TestQueryRewriter.java
> Added date range aggregation

- .gitignore
- docker/elasticsearch/Dockerfile
- docker/postgres/Dockerfile
- elasticsearch/pom.xml
- elasticsearch/src/main/java/com/tcdi/zombodb/query_parser/ASTIndexLink.java
- elasticsearch/src/main/java/com/tcdi/zombodb/query_parser/IndexMetadataManager.java
- elasticsearch/src/main/java/com/tcdi/zombodb/query_parser/QueryRewriter.java
- pom.xml
- postgres/pom.xml
- postgres/src/main/sql/zombodb--2.6.4--2.6.5.sql
- postgres/src/test/expected/issue-83.out
- postgres/src/test/sql/issue-83.sql
- postgres/src/test/tests.list
- postgres/zombodb.control
This fixes Issue #83 and bumps the version to 2.6.5
> Resolve issue #83

- .gitignore
- docker/elasticsearch/Dockerfile
- docker/postgres/Dockerfile
- elasticsearch/pom.xml
- pom.xml
- postgres/pom.xml
- postgres/src/main/sql/zombodb--2.6.7--2.6.8.sql
- postgres/src/main/sql/zombodb.sql
- postgres/src/test/expected/determine-index2.out
- postgres/src/test/expected/expansions.out
- postgres/src/test/expected/issue-29.out
- postgres/src/test/expected/issue-32.out
- postgres/src/test/expected/issue-63.out
- postgres/src/test/expected/issue-69-terms.out
- postgres/src/test/expected/issue-77.out
- postgres/src/test/expected/issue-85.out
- postgres/zombodb.control
> addressing issue #95:  don't force returned term values to uppercase

- local-ci/Dockerfile
Otherwise - "Unable to locate package wget""
> Update a container first

- docker/elasticsearch/Dockerfile
> Update ES plugin in dockerfile to V3.1.0

- elasticsearch/src/main/java/com/tcdi/zombodb/query_parser/optimizers/ExpansionOptimizer.java
- elasticsearch/src/main/java/com/tcdi/zombodb/query_parser/rewriters/QueryRewriter.java
- elasticsearch/src/main/java/com/tcdi/zombodb/query_parser/rewriters/SirenQueryRewriter.java
- elasticsearch/src/test/java/com/tcdi/zombodb/query_parser/TestQueryRewriter.java
- postgres/Makefile
- postgres/src/test/expected/issue-159.out
- postgres/src/test/sql/issue-159.sql
- postgres/src/test/tests.list
> FIX:  Issue #159

- .gitignore
- docker/elasticsearch/Dockerfile
- docker/postgres/Dockerfile
- elasticsearch/pom.xml
- elasticsearch/src/main/resources/es-plugin.properties
- pom.xml
- postgres/pom.xml
- postgres/src/main/c/am/elasticsearch.c
- postgres/src/main/c/am/zdbam.c
- postgres/src/main/sql/zombodb--3.1.4--3.1.5.sql
- postgres/src/test/expected/issue-169.out
- postgres/src/test/sql/issue-169.sql
- postgres/src/test/tests.list
- postgres/zombodb.control
> Fix Issue #169

- elasticsearch/src/main/java/com/tcdi/zombodb/query_parser/metadata/FieldAndIndexPair.java
- elasticsearch/src/main/java/com/tcdi/zombodb/query_parser/metadata/IndexMetadataManager.java
- elasticsearch/src/main/java/com/tcdi/zombodb/query_parser/optimizers/IndexLinkOptimizer.java
- elasticsearch/src/main/java/com/tcdi/zombodb/query_parser/optimizers/QueryTreeOptimizer.java
- elasticsearch/src/test/java/com/tcdi/zombodb/query_parser/TestQueryRewriter.java
- elasticsearch/src/test/resources/com/tcdi/zombodb/query_parser/testComplexQueryAST.expected
- elasticsearch/src/test/resources/com/tcdi/zombodb/query_parser/testComplexQueryJson.expected
- postgres/src/test/expected/issue-175.out
- postgres/src/test/expected/multi-search.out
- postgres/src/test/sql/issue-175.sql
- postgres/src/test/tests.list
This fixes issue #175.  I want to see travis-ci confirm before I merge and release.
> this fixes issue #175

- postgres/src/test/zdbtaptests/tests/fulltext.sql
stresses the SIREn ES plugin cache
> more fulltext tests

- INDEX-MANAGEMENT.md
- postgres/src/main/c/am/elasticsearch.c
- postgres/src/main/c/am/zdb_interface.c
- postgres/src/main/c/am/zdb_interface.h
- postgres/src/main/c/am/zdbam.c
and introduce a new GUC called `zombodb.log_level`
> implement issue #187: change ZDB's default log level to DEBUG1 

- elasticsearch/src/main/java/llc/zombodb/query_parser/metadata/IndexMetadata.java
- elasticsearch/src/main/java/llc/zombodb/query_parser/metadata/IndexMetadataManager.java
- postgres/src/test/expected/issue-251.out
- postgres/src/test/sql/issue-251.sql
- postgres/src/test/tests.list
This fixes issue #251, which turned out to be about ZDB's inability to property determine the analyzer/normalizer used for fields within nested objects.
> fixing issue #251

- elasticsearch/src/main/jjtree/com/tcdi/elasticsearch/query_parser/QueryParser.jjt
- elasticsearch/src/test/java/llc/zombodb/query_parser/TestQueryRewriter.java
fixing https://github.com/zombodb/zombodb/issues/306
> Fix parsing raw JSON query

- src/c/indexam/zdbam.c
- src/test/expected/issue-373.out
- src/test/sql/issue-373.sql
This fixes a segfault related to subtransaction handling
> fixing issue #373

- AGGREGATIONS.md
- BINARY-INSTALLATION.md
- CROSS-INDEX-JOINS.md
- INDEX-MANAGEMENT.md
- README.md
- SQL-FUNCTIONS.md
- TUTORIAL.md
Going to keep this open as we cleanup documentation.  Would prefer to have all the obvious doc changes in once place for easier review
> WIP:  Issue #606 -- cleaning up docs

- docker-build-system/build.sh
- docker-build-system/collect-artifacts.sh
- docker-build-system/package.sh
- docker-build-system/zombodb-build-alpine-3.12/Dockerfile
only supports PG13 at the moment, will need to find a way to build from different images instead of a single one
> Dockerfile for build system on Alpine

- CONFIGURATION-SETTINGS.md
- QUERY-BUILDER-API.md
- THINGS-TO-KNOW.md
Let's make the documentation a little better.
> Update docs about *row_estimate

- src/zql/ast.rs
- src/zql/dsl/mod.rs
- src/zql/mod.rs
- src/zql/transformations/nested_groups.rs
- test/expected/issue-739.out
- test/sql/issue-739.sql
Working on fixing issue #739.  The code is fixed.  Need tests next.
> fix issue #739

- src/zql/dsl/mod.rs
- src/zql/transformations/prox_rewriter.rs
- test/sql/issue-790.sql
This wants #787 to be merged first.
> Fix Issue #790

- src/highlighting/document_highlighter.rs
- test/expected/issue-792.out
- test/sql/issue-792.sql
Only have a test case so far, no actual code changes.
> Fix issue #792 - Properly Highlight `ProximityChain`s

- sql/_bootstrap.sql
... for all these years.  Which will cause problems if there is an existing value.
> fix issue #821 - we've been formatting the `session_preload_libraries` GUC incorrectly

- Cargo.lock
- Cargo.toml
- docker-build-system/Cargo.lock
- docker-build-system/Cargo.toml
- src/elasticsearch/analyze.rs
- src/elasticsearch/mod.rs
- src/json/builder.rs
- src/json/json_string.rs
- src/misc/timestamp_support.rs
- src/query_dsl/datetime_range.rs
- src/query_dsl/matches.rs
- src/query_dsl/more_like_this.rs
- src/query_dsl/query_string.rs
- test/expected/issue-770.out
- test/sql/issue-770.sql
- test/sql/test-date-time-serialization.sql
There was a bit of attention to date/time handling here, specifically converting the values to json.  A few of the existing regression tests have been updated to account for the changes.
> Upgrade to pgrx 0.9.3

- src/access_method/vacuum.rs
Previously, the (auto)VACUUM process would send everything it needs to do to Elasticsearch in a single `_bulk` request.  This could lead to those individual actions happening out-of-order, causing the VACUUM process to raise an ERROR and then leaving the index in an inconsistent state.
This serializes the requests into 4 individual `_bulk` requests.
> Serialize VACUUM requests

- Cargo.lock
- Cargo.toml
- docker-build-system/Cargo.lock
- docker-build-system/Cargo.toml
- test/expected/issue-854.out
- test/sql/issue-854.sql
This fixes #854 by upgrading pgrx to 0.9.7.
> Fix Issue #854

- src/highlighting/document_highlighter.rs
- src/highlighting/query_highlighter.rs
- test/expected/issue-859.out
- test/sql/issue-859.sql
fix issue https://github.com/zombodb/zombodb/issues/859: zdb.highlight_document() shouldn't reject documents that have a NULL field value when the query looks for that.
> Fix Issue #859

- src/highlighting/query_highlighter.rs
- test/expected/issue-889.out
- test/sql/issue-889.sql
This properly expands index field lists prior to hit highlighting.
> fix issue #889
